Add nginx to prod config
SpiskiApp/SpiskiApp pull request #4
Opened 2020-10-16 10:39 UTC by spiski

2020-10-16 21:05 UTC, ipaapa requested changes

2020-10-16 21:05 UTC, ipaapa commented on .github/workflows/prod.yml
> +            if curl -sS http://localhost/healthcheck; then
here you need to request to `:8000` as by default it utilizes `:80` and nginx is not running who can proxy it to 8000. Or maybe in this case it's better to start `nginx` and then send the request to `:80` and it should be OK

2020-10-17 17:57 UTC, spiski commented
Fixes #1

2020-10-17 19:25 UTC, chiselko6 approved these changes

2020-10-17 19:29 UTC, merged